version: '3'
services:
# The Database
    database:

        container_name: mysql_database

        image: mysql:8.0

        volumes:
            - dbdata:/var/lib/mysql
            - ./docker-compose/dev/mysql:/docker-entrypoint-initdb.d

        environment:

            - 

            - “MYSQL_Paswordddddddd=”

            - "MYSQL_ALLOW_E_PASSWORD=true"

        ports:
--no funciona 
            - 3306:3306

#The Application

    app:
        image: todo_list
        container_name: todo_list
        command: "npm run dev"
           
        depends_on:
            - "database"
        build:

            context: ./

            dockerfile: docker-compose/dev.dockerfile

        volumes:
            - ./src:/home/node/app/src
            - ./prisma:/home/node/app/prisma
            - ./docker-cker-compose
            - ./package-locke/node/app/package-lock.json
            -p/package.json

        ports: 
            - 4000:4000
volumes:
    dbdata:


